apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ads-app-access
  labels:
    component: ads
    module: app
spec:
  podSelector:
    matchLabels:
      component: ads
      module: app
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx-ingress 
          component: controller 
          origin: gardener
      namespaceSelector:
        matchLabels:
          name: kube-system  
  egress:
  - to:
    - podSelector:
        matchLabels:
          component: ads
          module: db
    - podSelector:
        matchLabels:
          component: users
          module: app
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
      namespaceSelector:
        matchLabels:
          name: kube-system

